version: 0.2

#env:
  #variables:
     # key: "value"
     # key: "value"
  #parameter-store:
     # key: "value"
     # key: "value"

phases:
  install:
    commands:
      - pip3 install -r requirements.txt -t .
      - apt install zip
  #pre_build:
    #commands:
      # - command
      # - command
  build:
    commands:
      - zip -r code.zip .
      # - command
  post_build:
    commands:
      - aws s3 cp code.zip s3://faraz-raw-bucket/
      # - command
artifacts:
  files:
    - lambda-template.yaml
    # - location
  #name: $(date +%Y-%m-%d)
  #discard-paths: yes
  #base-directory: location
#cache:
  #paths:
    # - paths