AWSTemplateFormatVersion: 2010-09-09
Description: Launching an instance.
Mappings:
  RegionMap:
    us-east-1:
      AMI: 'ami-035be7bafff33b6b6'
Resources: 
  myEC2:
    Type: AWS::EC2::Instance
    Properties:
      KeyName: !Ref keyname
      InstanceType: t2.micro
      SecurityGroupIds:
        - !Ref fmSecurityGroup 
      ImageId:
        Fn::FindInMap:
            - RegionMap
            - Ref: AWS::Region
            - AMI
      UserData: 
        Fn::Base64:
          Fn::Join:
          - ''
          - - "#!/bin/bash -xe\n"
            - echo 'Downloading PIP'
            - curl -O https://bootstrap.pypa.io/get-pip.py'
            - echo 'Executing PIP using Python'
            - python get-pip.py'
            - echo 'Setting PIP Classpath'
            - echo 'export PATH=~/.local/bin:$PATH' >> ~/.bash_profile
            - echo 'Reloading bash_profile'
            - source ~/.bash_profile
            - echo 'Installing AWS CLI'
            - pip install awscli
      Tags:
        - Key: Name
          Value: faraz-ec2-yaml-cf  
  fmSecurityGroup:
    Type: 'AWS::EC2::SecurityGroup'
    Properties:
      GroupDescription: Enables ssh on port 22
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: '22'
          ToPort: '22'
          CidrIp: 0.0.0.0/0
Parameters:
  keyname:
    Description: ec2-ssh key
    Type: String
Outputs:
  EC2output:
    Description: Public IP of the instance.
    Value: !GetAtt myEC2.PublicIp